project:
  type: website
  output-dir: docs

header-include:
  - \usepackage{<packages>}  # LaTex

website:
  title: "PHYSECON"
  page-footer: |
    &copy; 2026 Eugenio Net. | 
      [PDF script](https://eugenionet.github.io/physecon/index.pdf) |
      Update at [eugenionet.github.io/physecon](https://eugenionet.github.io/physecon/) | 
      [Contact](mailto:eugenionetweb@gmail.com?subject=Working%20Paper%20Economy-Physics&body=Body%20text) to collaborate
  navbar:
    background: MidnightBlue   # primary  # Navy 
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dummy.qmd
        text: Contribute
      - href: mailto:eugenionetweb@gmail.com?subject=Working%20Paper%20Economy-Physics&body=Body%20text
        text: Contact
      - href: https://www.researchgate.net/login?_sg=GVPRQCDS6NDU-YgTVOp8WJPPcGkOTjrVnKYT-SENPkZYSmRb9li_cjw9cbtoFy1MrMYmNVUez5YPVsOwZ8UvUQ&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6ImluZGV4IiwicGFnZSI6ImluZGV4IiwicG9zaXRpb24iOiJnbG9iYWxIZWFkZXIifX0
        target: "_blank"
        text: ResearchGate
    tools:
      - icon: feather   # https://icons.getbootstrap.com/
        menu:
          - text: SageMath
            href:  https://cocalc.com/
            target: "_blank"
          - text: WolframAlpha
            href:  https://www.wolframalpha.com/
            target: "_blank"
          - text: Datasette
            href:  https://datasette.io/
            target: "_blank"
          - text: Mathcha
            href:  https://www.mathcha.io/
            target: "_blank"
          - text: GeoGebra
            href:  https://www.geogebra.org/
            target: "_blank"
          - text: Chemical Elements
            href: https://ptable.com/?lang=en#Properties # https://periodic-table.rsc.org/
            target: "_blank"
          - text: Economy Fundamentals
            href: https://socialsci.libretexts.org/Bookshelves/Economics/Introductory_Comprehensive_Economics/Economics_(Boundless)/01%3A_Principles_of_Economics/1.06%3A_Differences_Between_Macroeconomics_and_Microeconomics
            target: "_blank"
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Synopsis"
        href: dummy.qmd
      - section: "Projects"
        contents:
          - text: "PhysEcon"
            href: index.qmd
          - text: "PhysFina"
            href: dummy.qmd
      - section: "Topics"
        contents:
          - text: "Periodicity"
            href: Content/2pi.qmd
          - text: "Velocity - Movement of Matter in Space and Time"
            href: Content/lightspeed.qmd
          - text: "Matter and Refraction"
            href: Content/refraction.qmd
          - text: "Metric"
            href: Content/metric.qmd
          - text: "Finestructure"
            href: Content/finestructure.qmd
          - text: "Static, Kinetic, Dynamic"
            href: dummy.qmd
          - text: "Lagrange-Hamilton"
            href: dummy.qmd
          - text: "Space Time Matter"
            href: dummy.qmd
          - text: "Degrees of Freedom"
            href: dummy.qmd
          - text: "Movement & State"
            href: dummy.qmd
          - text: "Restrictions & Constraints, Boundries & Limitations"
            href: dummy.qmd
          - text: "Equilibrium & Laborsystem"
            href: dummy.qmd
          - text: "Work & Energy, Information"
            href: dummy.qmd
          - text: "Force and Momenta"
            href: dummy.qmd
          - text: "Entropy & Enthalpy"
            href: dummy.qmd
          - text: "Symmetry & Conservation"
            href: dummy.qmd
          - text: "Reversability"
            href: dummy.qmd
          - text: "Refraction & Medium"
            href: dummy.qmd
          - text: "Action & Path"
            href: dummy.qmd
          - text: "Potentials"
            href: dummy.qmd
          - text: "Renormalization"
            href: dummy.qmd
          - text: "Continum & Quantum"
            href: dummy.qmd
          - text: "Probability, Liklyhood & Prediction"
            href: dummy.qmd
          - text: "Optimization & Variation"
            href: dummy.qmd
          - text: "Micro & Macro"
            href: dummy.qmd
      - section: "Resources"
        href: dummy.qmd
        contents:
          - text: "Sources"
            href: dummy.qmd


format:
  pdf:      #TERMINAL: quarto install tinytex
    toc: true
#    default
#    documentclass: book    # book    # article    # scrartcl
    include-in-header: 
      text:
        \usepackage{hyperref, mathtools, amsmath, scrlayer-scrpage}
        \rohead{
          \hrule
        }
        \lofoot{
          \vspace*{10px} \hrule 
          \tiny{
            \vspace*{3px} 
            \copyright \ \
            Update at \href{https://eugenionet.github.io/physecon/}{eugenionet.github.io/physecon}
            }
        }
  html:
    page-layout: article    # full  # custom
    keep-tex: false
#    include-in-header: 
#      - text: \usepackage{mathtools, amsmath} 
    respect-user-color-scheme: true
    theme:
      light: [Cerulean, theme-light.scss] 
      dark: [Cerulean, theme-dark.scss]    # Morph  # Slate   # darkly
#      - Cerulean
#      - brand
    css: styles.css
    toc: true
    toc-title: "Content"
    toc-location: right
#    linkcolor: grey    # urlcolor: green
#    subtitle: numbered
#    smooth-scroll: true
    number-sections: true

other-links:
  - text: "see also"
    href: https://quarto.org/docs/output-formats/html-basics.html
  





